### ISSUE TITLE
Refactor Global Objects to Interior Synchronization

### ISSUE THREAD

**Issue by andrew-pa** [andrew-pa/k#3]
Interior synchronization is more performant and makes it easier to write safe interrupt handlers that won't deadlock.

## TODO
- [ ] Physical Memory Allocator
- [ ] Virtual Address Allocator
- [ ] Thread Scheduler
- [ ] Registry
- [ ] System call/Interrupt handler tables (could probably be read-only after initialization)
- [ ] Interrupt Controller
